portfolio/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/about'

   
end

portfolio/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

portfolio/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

portfolio/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

portfolio/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

portfolio/app/helpers/about_helper.rb
module AboutHelper
end

portfolio/app/helpers/application_helper.rb
module ApplicationHelper
end

portfolio/app/helpers/content_helper.rb
module ContentHelper
end

portfolio/app/helpers/home_helper.rb
module HomeHelper
end

portfolio/app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

portfolio/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Portfolio</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">me</a>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> -->
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

portfolio/app/views/home/about.html.erb
<%= render 'home/header' %>
<h1>About ME</h1>
<p>My name is Matthew and I create app</p>
<%= link_to 'Home Page' , root_path, class: 'btn btn-primary' %>

portfolio/app/views/home/index.html.erb
<%= render 'home/header' %>
<div class="jumbotron">
	<h1>Welcome to my site</h1>
	<p>Somwhere it will blows sb mind</p>
	<%= link_to 'About Page' , home_about_path, class: 'btn btn-success' %>
</div>

portfolio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>